### ISSUE TITLE
bug(clippy): arguments are unused in `#[gprogram]`'s constructors

### ISSUE THREAD

**Issue by breathx** [gear-tech/sails#261] opened 2024-05-20 17:27 UTC

**Comment by vobradovich** [comment] 2024-05-21 09:28
Is it a duplicate https://github.com/gear-tech/sails/issues/183?

**Comment by DennisInSky** [comment] 2024-05-28 14:44
Apparently this is a duplicate of #183

**Closed as completed by DennisInSky** 2024-05-28 14:44 UTC
